# Generated by Django 2.2.4 on 2021-03-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_wish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
